run:
  timeout: 5m
  skip-files:
    - generated.*
    - mage.*

linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
    - errcheck
  disable:
    - unparam
    - structcheck
